### ISSUE TITLE
Error: no such column: version

### ISSUE THREAD

**Issue by BachoSeven** [Polochon-street/blissify-rs#24]
Upon compiling the latest git master, I got this:

```
 blissify update ~/slsk/music
Error: no such column: version

Caused by:
    Error code 1: SQL error or missing database
```

Using `list-db` gives a similar error:

```
blissify list-db
Error: no such column: version

Caused by:
    Error code 1: SQL error or missing database

```

The db is there:
``` sh
~/.local/share/bliss-rs  ls
songs.db

```

**Comment by Polochon-street** [comment]
Hi,

You should be able to fix it by running `sqlite3 ~/.local/share/bliss-rs/songs.db` and then `alter table song add column version not null default 1;` in the prompt.

I should've bumped the major version number or documented it somewhere, I'll see what I can do about it. If it really doesn't work for some reason you can probably also `rescan` the db, but you probably don't want to spend 2 extra hours doing that.

**Comment by BachoSeven** [comment]
Thanks, that worked perfectly :)
