### ISSUE TITLE
ffmpeg 5.0

### ISSUE THREAD

**Issue by toofar** [Polochon-street/blissify-rs#25]
It look like blissify hasn't been updated to build against ffmpeg 5.0? I tried to follow the instructions in the readme (I'm on debian sid) and I had to install libavfilter-dev and libavdevice-dev in addition to the stuff already noted in the readme. But then I got stuck on `fatal error: '/usr/include/libavcodec/vaapi.h' file not found`.

**Comment by Polochon-street** [comment]
Hi,

I've bumped bliss' version, which should in turn make it work with ffmpeg 5.1. Hopefully that should fix it for you :)

**Comment by toofar** [comment]
Thank you, it is churning away happily now. I've been looking for something that could do music similarity based playlists and didn't required tight integration with my music library for a while now so I look forward to playing with this!
