### ISSUE TITLE
Fail to compile (fedora 37)

### ISSUE THREAD

**Issue by kbridger** [Polochon-street/blissify-rs#35]
I'm following the installation instructions from https://crates.io/crates/blissify and the compilation is failing.  I'm not familiar with rust of blissify beyond being a huge fan of blissify.  I had this running on F36, but F37 seems to fail.  Might just be because I haven't got a correct Fedora dependency installed yet.

My basic knowledge says it can't find limits.h, but I've confirmed the file exists.  Should I be using sudo to build the tool?

Pastebin: https://pastebin.com/UcKywNMZ

```
  --- stderr
  /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found
  /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /home/kirk/.cargo/registry/src/github.com-1ecc6299db9ec823/ffmpeg-sys-next-5.1.1/build.rs:1290:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `blissify v0.3.3`, intermediate artifacts can be found at `/tmp/cargo-installiTZ8JQ`
```

**Comment by Polochon-street** [comment]
Hi!
It seems that you hit this https://github.com/meh/rust-ffmpeg-sys/issues/62, which would be solved by installing `clang`. Let's see if this works for you, otherwise I'll try to reproduce :)

**Comment by kbridger** [comment]
Ah, I installed sqlite-devel and that seems to have worked - looks like everything compiled!  Thanks!

**Comment by Polochon-street** [comment]
Awesome! Could you write down the exact packages you installed / commands you ran to get it to work, so I could add it to the readme? :)

**Comment by kbridger** [comment]
Sorry I wasn't notified about your reply, or I might have forgotten.

If I recall correctly it was just clang and sql-devel, and the 'history' command doesn't show anything else.  Thanks again fro your help!
