### ISSUE TITLE
[Documentation] Please clarify the README whether MPD is mandatory 

### ISSUE THREAD

**Issue by rubyFeedback** [Polochon-street/blissify-rs#6]
Hello,

I am wondering if blissify can be used on a directory with .mp3 songs even without mpd,
e. g. just for generating a playlist or library; or whether MPD is mandatory. Thank you!

**Comment by Polochon-street** [comment]
Hi,

Indeed, you need to have MPD to use blissify.

If you know Rust, it shouldn't be too difficult to adapt https://github.com/Polochon-street/bliss-rs#make-a-playlist-from-a-song for a folder. If now, I'm working on a simple CLI tool to try it out on a folder :)

Cheers,
Paul

**Comment by Polochon-street** [comment]
Hi,
I've finally merged https://github.com/Polochon-street/bliss-rs/pull/25, which is the beginning of a simple CLI tool to analyze songs from a folder and make a playlist from a starting song.
Closing this issue :)
