### ISSUE TITLE
Feature request: dry-run mode

### ISSUE THREAD

**Issue by jcorporation** [Polochon-street/blissify-rs#60]
After my MPD database is now indexed by blissify, I want to integrate it in the myMPD jukebox function.

It will be cool if blissify provides a dry run mode. 

- Specify the starting song with a command line option
- Print the song uris that would be added to stdout

I can use the dry-run mode to fill the myMPD jukebox queue with songs blissify selects and it should be useful for others too.

**Comment by jcorporation** [comment]
Correct. I want to specify the path for the reference song and blissify should output the song that would be added to the queue.

I will parse the output and it to a internal queue of myMPD.

**Comment by Polochon-street** [comment]
I gave it a go here https://github.com/Polochon-street/blissify-rs/pull/62, tell me what you think before I merge :)

I'm still unsure whether the path should be relative to MPD_BASE_PATH or not, or whether I should even have a flag for that...

**Comment by jcorporation** [comment]
Great! I will test it soon. I would prefer a relative path for the output.

**Comment by jcorporation** [comment]
I tested it and it works as expected. As the --from-song expects the full path the output should be also with the full path to be consistent.

**Comment by Polochon-street** [comment]
Nice that it works. It should accept paths both from the full path but also from the MPD :)

Hope it'll work as expected for myMPD!

**Comment by Polochon-street** [comment]
hi @jcorporation, I've finally merged https://github.com/Polochon-street/blissify-rs/pull/62 after making some slight modifications to it (I put most of it in the README), tell me if it still works for you - if it does, I'll release a new version :)

**Comment by jcorporation** [comment]
It works as expected, thanks for implementing this feature.
